// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from category_items.proto

package nl.rootdev.android.kookjijclient2.datastructures.pb;

import java.io.IOException;

import nl.rootdev.android.kookjijclient2.datastructures.ICategoryItem;

import com.dyuproject.protostuff.me.Input;
import com.dyuproject.protostuff.me.Message;
import com.dyuproject.protostuff.me.Output;
import com.dyuproject.protostuff.me.Schema;
import com.dyuproject.protostuff.me.UninitializedMessageException;

public final class CategoryItem implements Message, Schema, ICategoryItem
{

    public static Schema getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static CategoryItem getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final CategoryItem DEFAULT_INSTANCE = new CategoryItem();

    
    private Long id;
    private String name;
    private Integer rating;
    private Long lastedit;

    public CategoryItem()
    {
        
    }

    public CategoryItem(
        Long id,
        String name,
        Long lastedit
    )
    {
        this.id = id;
        this.name = name;
        this.lastedit = lastedit;
    }

    // getters and setters

    // id

    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    // name

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    // rating

    public Integer getRating()
    {
        return rating;
    }

    public void setRating(Integer rating)
    {
        this.rating = rating;
    }

    // lastedit

    public Long getLastedit()
    {
        return lastedit;
    }

    public void setLastedit(Long lastedit)
    {
        this.lastedit = lastedit;
    }

    // message method

    public Schema cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public Object /*CategoryItem*/ newMessage()
    {
        return new CategoryItem();
    }

    public Class typeClass()
    {
        return CategoryItem.class;
    }

    public String messageName()
    {
        return "CategoryItem";
    }

    public String messageFullName()
    {
        return CategoryItem.class.getName();
    }

    public boolean isInitialized(Object /*CategoryItem*/ messageObj)
    {
        CategoryItem message = (CategoryItem)messageObj;
        return 
            message.id != null 
            && message.name != null 
            && message.lastedit != null;
    }

    public void mergeFrom(Input input, Object /*CategoryItem*/ messageObj) throws IOException
    {
        CategoryItem message = (CategoryItem)messageObj;
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.id = new Long(input.readUInt64());
                    break;
                case 2:
                    message.name = input.readString();
                    break;

                case 3:
                    message.rating = new Integer(input.readUInt32());
                    break;
                case 4:
                    message.lastedit = new Long(input.readUInt64());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }



    public void writeTo(Output output, Object /*CategoryItem*/ messageObj) throws IOException
    {
        CategoryItem message = (CategoryItem)messageObj;
        if(message.id == null)
            throw new UninitializedMessageException(message);
        output.writeUInt64(1, message.id.longValue(), false);

        if(message.name == null)
            throw new UninitializedMessageException(message);
        output.writeString(2, message.name, false);


        if(message.rating != null)
            output.writeUInt32(3, message.rating.intValue(), false);

        if(message.lastedit == null)
            throw new UninitializedMessageException(message);
        output.writeUInt64(4, message.lastedit.longValue(), false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "id";
            case 2: return "name";
            case 3: return "rating";
            case 4: return "lastedit";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = (Integer)__fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.Hashtable __fieldMap = new java.util.Hashtable();
    static
    {
        __fieldMap.put("id", new Integer(1));
        __fieldMap.put("name", new Integer(2));
        __fieldMap.put("rating", new Integer(3));
        __fieldMap.put("lastedit", new Integer(4));
    }
    
}
